FROM php:8.1-fpm
WORKDIR /var/www/html
COPY . .
RUN apt-get update \
&& apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip git unzip \
&& docker-php-ext-install pdo_mysql mbstring gd \
&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install
CMD ["php-fpm"]
EXPOSE 9000